// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	proto/auth/auth.proto

It has these top-level messages:
	User
	Request
	ResponseUser
	ResponseRole
	ResponseMenu
	ResponseToken
	Token
	Error
	Role
	Menu
	Badge
	Wrapper
	Atributes
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Company  string `protobuf:"bytes,3,opt,name=company" json:"company,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Token    string `protobuf:"bytes,6,opt,name=token" json:"token,omitempty"`
	// @inject_tag: gorm:"many2many:user_roles;foreignkey:id;association_foreignkey:id;association_jointable_foreignkey:role_id;jointable_foreignkey:user_id;"
	Roles []*Role `protobuf:"bytes,7,rep,name=roles" json:"roles,omitempty" gorm:"many2many:user_roles;foreignkey:id;association_foreignkey:id;association_jointable_foreignkey:role_id;jointable_foreignkey:user_id;"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ResponseUser struct {
	User   *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Users  []*User  `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
	Token  *Token   `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *ResponseUser) Reset()                    { *m = ResponseUser{} }
func (m *ResponseUser) String() string            { return proto.CompactTextString(m) }
func (*ResponseUser) ProtoMessage()               {}
func (*ResponseUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResponseUser) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResponseUser) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ResponseUser) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseUser) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type ResponseRole struct {
	Role   *Role    `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Roles  []*Role  `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseRole) Reset()                    { *m = ResponseRole{} }
func (m *ResponseRole) String() string            { return proto.CompactTextString(m) }
func (*ResponseRole) ProtoMessage()               {}
func (*ResponseRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ResponseRole) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *ResponseRole) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ResponseRole) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResponseMenu struct {
	Menu   *Menu    `protobuf:"bytes,1,opt,name=menu" json:"menu,omitempty"`
	Menues []*Menu  `protobuf:"bytes,2,rep,name=menues" json:"menues,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseMenu) Reset()                    { *m = ResponseMenu{} }
func (m *ResponseMenu) String() string            { return proto.CompactTextString(m) }
func (*ResponseMenu) ProtoMessage()               {}
func (*ResponseMenu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResponseMenu) GetMenu() *Menu {
	if m != nil {
		return m.Menu
	}
	return nil
}

func (m *ResponseMenu) GetMenues() []*Menu {
	if m != nil {
		return m.Menues
	}
	return nil
}

func (m *ResponseMenu) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResponseToken struct {
	Token  *Token   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	User   *User    `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResponseToken) Reset()                    { *m = ResponseToken{} }
func (m *ResponseToken) String() string            { return proto.CompactTextString(m) }
func (*ResponseToken) ProtoMessage()               {}
func (*ResponseToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ResponseToken) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ResponseToken) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResponseToken) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Token struct {
	Token  string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Valid  bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code        int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Role struct {
	Id    string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Users []*User `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
	// @inject_tag: gorm:"many2many:role_menus;foreignkey:id;association_foreignkey:id;association_jointable_foreignkey:menu_id;jointable_foreignkey:role_id;"
	Menues []*Menu `protobuf:"bytes,4,rep,name=menues" json:"menues,omitempty" gorm:"many2many:role_menus;foreignkey:id;association_foreignkey:id;association_jointable_foreignkey:menu_id;jointable_foreignkey:role_id;"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Role) GetMenues() []*Menu {
	if m != nil {
		return m.Menues
	}
	return nil
}

type Menu struct {
	Id      string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Url     string   `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Badge   *Badge   `protobuf:"bytes,4,opt,name=badge" json:"badge,omitempty"`
	Wrapper *Wrapper `protobuf:"bytes,5,opt,name=wrapper" json:"wrapper,omitempty"`
	Title   bool     `protobuf:"varint,6,opt,name=title" json:"title,omitempty"`
	// @inject_tag: gorm:"many2many:menu_childrens;foreignkey:id;association_foreignkey:id;association_jointable_foreignkey:children_id;jointable_foreignkey:parent_id;"
	Children  []*Menu `protobuf:"bytes,7,rep,name=children" json:"children,omitempty" gorm:"many2many:menu_childrens;foreignkey:id;association_foreignkey:id;association_jointable_foreignkey:children_id;jointable_foreignkey:parent_id;"`
	Icon      string  `protobuf:"bytes,8,opt,name=icon" json:"icon,omitempty"`
	Roles     []*Role `protobuf:"bytes,9,rep,name=roles" json:"roles,omitempty"`
	BadgeID   string  `protobuf:"bytes,10,opt,name=badgeID" json:"badgeID,omitempty"`
	WrapperID string  `protobuf:"bytes,11,opt,name=wrapperID" json:"wrapperID,omitempty"`
}

func (m *Menu) Reset()                    { *m = Menu{} }
func (m *Menu) String() string            { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()               {}
func (*Menu) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Menu) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Menu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Menu) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Menu) GetBadge() *Badge {
	if m != nil {
		return m.Badge
	}
	return nil
}

func (m *Menu) GetWrapper() *Wrapper {
	if m != nil {
		return m.Wrapper
	}
	return nil
}

func (m *Menu) GetTitle() bool {
	if m != nil {
		return m.Title
	}
	return false
}

func (m *Menu) GetChildren() []*Menu {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Menu) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Menu) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Menu) GetBadgeID() string {
	if m != nil {
		return m.BadgeID
	}
	return ""
}

func (m *Menu) GetWrapperID() string {
	if m != nil {
		return m.WrapperID
	}
	return ""
}

type Badge struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Variant string `protobuf:"bytes,2,opt,name=variant" json:"variant,omitempty"`
	Text    string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
}

func (m *Badge) Reset()                    { *m = Badge{} }
func (m *Badge) String() string            { return proto.CompactTextString(m) }
func (*Badge) ProtoMessage()               {}
func (*Badge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Badge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Badge) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

func (m *Badge) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Wrapper struct {
	Id          string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Element     string     `protobuf:"bytes,2,opt,name=element" json:"element,omitempty"`
	Atributes   *Atributes `protobuf:"bytes,3,opt,name=atributes" json:"atributes,omitempty"`
	AtributesID string     `protobuf:"bytes,4,opt,name=atributesID" json:"atributesID,omitempty"`
}

func (m *Wrapper) Reset()                    { *m = Wrapper{} }
func (m *Wrapper) String() string            { return proto.CompactTextString(m) }
func (*Wrapper) ProtoMessage()               {}
func (*Wrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Wrapper) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Wrapper) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *Wrapper) GetAtributes() *Atributes {
	if m != nil {
		return m.Atributes
	}
	return nil
}

func (m *Wrapper) GetAtributesID() string {
	if m != nil {
		return m.AtributesID
	}
	return ""
}

type Atributes struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Atributes) Reset()                    { *m = Atributes{} }
func (m *Atributes) String() string            { return proto.CompactTextString(m) }
func (*Atributes) ProtoMessage()               {}
func (*Atributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Atributes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*Request)(nil), "auth.Request")
	proto.RegisterType((*ResponseUser)(nil), "auth.ResponseUser")
	proto.RegisterType((*ResponseRole)(nil), "auth.ResponseRole")
	proto.RegisterType((*ResponseMenu)(nil), "auth.ResponseMenu")
	proto.RegisterType((*ResponseToken)(nil), "auth.ResponseToken")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*Error)(nil), "auth.Error")
	proto.RegisterType((*Role)(nil), "auth.Role")
	proto.RegisterType((*Menu)(nil), "auth.Menu")
	proto.RegisterType((*Badge)(nil), "auth.Badge")
	proto.RegisterType((*Wrapper)(nil), "auth.Wrapper")
	proto.RegisterType((*Atributes)(nil), "auth.Atributes")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0x8f, 0x1d, 0x27, 0x93, 0x06, 0xd0, 0x52, 0x24, 0xab, 0x20, 0x14, 0x8c, 0x44, 0x0b,
	0xa8, 0x05, 0xa5, 0x67, 0x0e, 0x81, 0x54, 0x51, 0x0f, 0xbd, 0xac, 0xf8, 0xbb, 0x6e, 0xe3, 0x11,
	0xb5, 0x70, 0x6c, 0xb3, 0x5e, 0xb7, 0x70, 0xe7, 0xc8, 0x03, 0xf0, 0x14, 0x9c, 0xe0, 0xfd, 0xd0,
	0xce, 0x6e, 0x6c, 0xa7, 0xe0, 0xca, 0x97, 0x78, 0xe7, 0x9b, 0xd9, 0x99, 0x6f, 0xfe, 0x56, 0x81,
	0x7b, 0x99, 0x4c, 0x55, 0xfa, 0x42, 0x14, 0xea, 0x82, 0x7e, 0x8e, 0x48, 0x66, 0x8e, 0x3e, 0x07,
	0xbf, 0xba, 0xe0, 0xbc, 0xcb, 0x51, 0xb2, 0x5b, 0xd0, 0x8b, 0x42, 0xbf, 0x3b, 0xed, 0x1e, 0x8c,
	0x78, 0x2f, 0x0a, 0x19, 0x03, 0x27, 0x11, 0x6b, 0xf4, 0x7b, 0x84, 0xd0, 0x99, 0xf9, 0xe0, 0xad,
	0xd2, 0x75, 0x26, 0x92, 0x6f, 0x7e, 0x9f, 0xe0, 0x8d, 0xc8, 0x76, 0xc1, 0xc5, 0xb5, 0x88, 0x62,
	0xdf, 0x21, 0xdc, 0x08, 0x6c, 0x0f, 0x86, 0x99, 0xc8, 0xf3, 0xab, 0x54, 0x86, 0xbe, 0x4b, 0x8a,
	0x52, 0xd6, 0x37, 0x54, 0xfa, 0x19, 0x13, 0x7f, 0x60, 0x6e, 0x90, 0xc0, 0xa6, 0xe0, 0xca, 0x34,
	0xc6, 0xdc, 0xf7, 0xa6, 0xfd, 0x83, 0xf1, 0x0c, 0x8e, 0x88, 0x30, 0x4f, 0x63, 0xe4, 0x46, 0x11,
	0x8c, 0xc0, 0xe3, 0xf8, 0xa5, 0xc0, 0x5c, 0x05, 0x3f, 0xbb, 0xb0, 0xc3, 0x31, 0xcf, 0xd2, 0x24,
	0x47, 0xca, 0xe1, 0x21, 0x38, 0x45, 0x8e, 0x92, 0xb2, 0x28, 0x2f, 0x6b, 0x0d, 0x27, 0x5c, 0x7b,
	0xd7, 0xdf, 0xdc, 0xef, 0xd5, 0xbd, 0x93, 0x81, 0x51, 0xb0, 0xc7, 0x30, 0x40, 0x29, 0x53, 0x99,
	0xfb, 0x7d, 0x32, 0x19, 0x1b, 0x93, 0x13, 0x8d, 0x71, 0xab, 0x62, 0x8f, 0x36, 0xd4, 0x1d, 0x8a,
	0x63, 0x6d, 0xde, 0x6a, 0xc8, 0xe6, 0x11, 0x14, 0x15, 0x33, 0x4d, 0x5e, 0x33, 0xd3, 0xf4, 0xb7,
	0x99, 0x51, 0x5a, 0x84, 0x57, 0x79, 0xf7, 0x1a, 0xf2, 0x6e, 0xc5, 0x2c, 0xb8, 0xaa, 0xc2, 0x9e,
	0x61, 0x52, 0xe8, 0xb0, 0x6b, 0x4c, 0x8a, 0xed, 0xb0, 0x5a, 0xc3, 0x09, 0x67, 0x01, 0x0c, 0xf4,
	0xf7, 0x7a, 0x5c, 0xb2, 0xb0, 0x9a, 0xb6, 0x81, 0x27, 0x9b, 0xc0, 0x54, 0x87, 0xaa, 0x46, 0xdd,
	0xa6, 0x1a, 0x95, 0xdd, 0xea, 0x35, 0x74, 0xab, 0x55, 0xe0, 0x8f, 0xe0, 0x9a, 0x80, 0xbb, 0xf5,
	0x80, 0xe5, 0x3c, 0xed, 0x82, 0x7b, 0x29, 0xe2, 0x28, 0xa4, 0x20, 0x43, 0x6e, 0x84, 0x76, 0x9e,
	0x5f, 0x81, 0x4b, 0x80, 0xde, 0x84, 0x55, 0x1a, 0x9a, 0xde, 0xb9, 0x9c, 0xce, 0x6c, 0x0a, 0xe3,
	0x10, 0xf3, 0x95, 0x8c, 0x32, 0x15, 0xa5, 0x89, 0x5d, 0x92, 0x3a, 0x14, 0x64, 0xe0, 0x50, 0xe7,
	0xdb, 0xec, 0x55, 0x39, 0x97, 0xfd, 0xa6, 0xb9, 0xac, 0x1a, 0xe5, 0x34, 0x35, 0x2a, 0xf8, 0xdd,
	0x03, 0x87, 0xba, 0xde, 0x26, 0xe4, 0x1d, 0xe8, 0x17, 0x32, 0xb6, 0x6b, 0xac, 0x8f, 0xba, 0x63,
	0xe7, 0x22, 0xfc, 0x84, 0xdb, 0x53, 0xfd, 0x5a, 0x43, 0xdc, 0x68, 0xd8, 0x3e, 0x78, 0x57, 0x52,
	0x64, 0x19, 0x4a, 0x5a, 0xe7, 0xf1, 0x6c, 0x62, 0x8c, 0x3e, 0x18, 0x90, 0x6f, 0xb4, 0xd4, 0x8c,
	0x48, 0xc5, 0x48, 0xcb, 0x3d, 0xe4, 0x46, 0x60, 0x4f, 0x60, 0xb8, 0xba, 0x88, 0xe2, 0x50, 0x62,
	0xb2, 0xbd, 0xdf, 0x94, 0x46, 0xa9, 0xd3, 0x7c, 0xa3, 0x55, 0x9a, 0xf8, 0x43, 0xc3, 0x57, 0x9f,
	0xab, 0x05, 0x19, 0x35, 0x2d, 0x88, 0x0f, 0x1e, 0xb1, 0x3c, 0x5d, 0xf8, 0x60, 0x1e, 0x27, 0x2b,
	0xb2, 0x07, 0x30, 0xb2, 0xc4, 0x4e, 0x17, 0xfe, 0x98, 0x74, 0x15, 0x10, 0x9c, 0x80, 0x4b, 0x49,
	0xfe, 0x53, 0x36, 0x1f, 0xbc, 0x4b, 0x21, 0x23, 0x91, 0x28, 0x5b, 0xb9, 0x8d, 0xa8, 0x09, 0x2a,
	0xfc, 0xaa, 0x6c, 0xf5, 0xe8, 0x1c, 0x7c, 0xef, 0x82, 0x67, 0xeb, 0xf0, 0x3f, 0x4f, 0x18, 0xe3,
	0x1a, 0x2b, 0x4f, 0x56, 0x64, 0x87, 0x30, 0x12, 0x4a, 0x46, 0xe7, 0x85, 0xc2, 0x9c, 0xdc, 0x8d,
	0x67, 0xb7, 0x4d, 0x6a, 0xf3, 0x0d, 0xcc, 0x2b, 0x0b, 0x3d, 0x76, 0xa5, 0x70, 0xba, 0xb0, 0x8f,
	0x6d, 0x1d, 0x0a, 0xee, 0xc3, 0xa8, 0xbc, 0x79, 0x9d, 0xc7, 0xec, 0x4f, 0x17, 0x9c, 0x79, 0xa1,
	0x2e, 0xd8, 0x33, 0x18, 0xbc, 0x91, 0x28, 0x14, 0xb2, 0xda, 0xac, 0xed, 0x31, 0x5b, 0xd4, 0xda,
	0x93, 0x1a, 0x74, 0xd8, 0x3e, 0xf4, 0x97, 0xa8, 0x5a, 0x18, 0x1e, 0xc2, 0x60, 0x89, 0x6a, 0x1e,
	0xc7, 0x6c, 0xb2, 0xd1, 0xd3, 0x3b, 0xdd, 0x60, 0xfe, 0xd4, 0x72, 0xa9, 0x3b, 0xbe, 0xbb, 0x6d,
	0x49, 0x9b, 0x1d, 0x74, 0x66, 0x3f, 0xfa, 0x30, 0xd4, 0xfa, 0x85, 0x50, 0x82, 0xbd, 0x84, 0x9d,
	0x25, 0x2a, 0x2d, 0xea, 0xb1, 0xc9, 0x6f, 0x22, 0xa6, 0x0d, 0x82, 0x0e, 0x7b, 0x0e, 0x93, 0xf7,
	0x7a, 0xef, 0x85, 0xb2, 0x8f, 0x53, 0xfd, 0x35, 0xda, 0xab, 0x0b, 0x41, 0x87, 0x1d, 0x01, 0x98,
	0xd2, 0xd0, 0xf6, 0xd6, 0xe6, 0xec, 0xba, 0x73, 0x8d, 0x91, 0x73, 0x6f, 0x89, 0xaa, 0xa5, 0xf1,
	0x0c, 0xc6, 0xa6, 0x44, 0x9c, 0x46, 0xf6, 0xe6, 0x3a, 0xd9, 0x3b, 0x25, 0x21, 0xda, 0xed, 0xda,
	0xc6, 0x34, 0x66, 0xab, 0x09, 0xb5, 0x34, 0x3e, 0xa6, 0x62, 0xce, 0xe3, 0xf8, 0xcc, 0x3c, 0xf6,
	0x37, 0x33, 0x32, 0x97, 0xce, 0x07, 0xf4, 0x07, 0xe2, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x6e, 0x3e, 0xa7, 0xf2, 0x59, 0x08, 0x00, 0x00,
}
